using Core.Result;
using MediatR;
using Microsoft.Extensions.Logging;
using Payments.Domain.Repositories;
using Shared.Contracts.DTOs.Blockchain;
using Shared.Contracts.Queries;

namespace Payments.Application.Queries.GetPaymentBlockchainDetails;

public class GetPaymentBlockchainDetailsQueryHandler : IRequestHandler<GetPaymentBlockchainDetailsQuery, Result<PaymentBlockchainDTO>>
{
    private readonly IPaymentRepository _paymentRepository;
    private readonly IPaymentMethodRepository _paymentMethodRepository;
    private readonly IPaymentStatusRepository _paymentStatusRepository;
    private readonly ILogger<GetPaymentBlockchainDetailsQueryHandler> _logger;

    public GetPaymentBlockchainDetailsQueryHandler(
        IPaymentRepository paymentRepository,
        IPaymentMethodRepository paymentMethodRepository,
        IPaymentStatusRepository paymentStatusRepository,
        ILogger<GetPaymentBlockchainDetailsQueryHandler> logger)
    {
        _paymentRepository = paymentRepository;
        _paymentMethodRepository = paymentMethodRepository;
        _paymentStatusRepository = paymentStatusRepository;
        _logger = logger;
    }

    public async Task<Result<PaymentBlockchainDTO>> Handle(GetPaymentBlockchainDetailsQuery request, CancellationToken cancellationToken)
    {
        try
        {
            // Get payment details
            var payment = await _paymentRepository.GetByIdAsync(request.PaymentId);
            if (payment == null)
            {
                return Result<PaymentBlockchainDTO>.Fail(
                    message: "Payment not found",
                    errorType: "PaymentNotFound",
                    resultStatus: ResultStatus.NotFound);
            }

            // Get payment method details
            var paymentMethod = await _paymentMethodRepository.GetByIdAsync(payment.PaymentMethodId);
            if (paymentMethod == null)
            {
                _logger.LogError("Payment method not found for ID: {PaymentMethodId}", payment.PaymentMethodId);
                return Result<PaymentBlockchainDTO>.Fail(
                    message: "Payment method not found",
                    errorType: "PaymentMethodNotFound",
                    resultStatus: ResultStatus.Failed);
            }

            // Get payment status details
            var paymentStatus = await _paymentStatusRepository.GetByIdAsync(payment.StatusId);
            if (paymentStatus == null)
            {
                _logger.LogError("Payment status not found for ID: {StatusId}", payment.StatusId);
                return Result<PaymentBlockchainDTO>.Fail(
                    message: "Payment status not found",
                    errorType: "PaymentStatusNotFound",
                    resultStatus: ResultStatus.Failed);
            }

            // Create blockchain DTO
            var paymentBlockchainDTO = new PaymentBlockchainDTO
            {
                PaymentId = payment.Id,
                OrderId = payment.OrderId,
                Amount = payment.Amount,
                PaymentMethod = paymentMethod.Name,
                PaymentStatus = paymentStatus.Name,
                TransactionDate = payment.CreatedAt,
                TransactionHash = GenerateTransactionHash(payment.Id, payment.CreatedAt),
                PaymentDetails = $"Payment processed via {paymentMethod.Name} on {payment.CreatedAt:yyyy-MM-dd HH:mm:ss}"
            };

            return Result<PaymentBlockchainDTO>.Ok(
                data: paymentBlockchainDTO,
                message: "Payment blockchain details retrieved successfully",
                resultStatus: ResultStatus.Success);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error retrieving blockchain payment details for payment {PaymentId}", request.PaymentId);
            return Result<PaymentBlockchainDTO>.Fail(
                message: "Error retrieving payment details",
                errorType: "GetPaymentDetailsFailed",
                resultStatus: ResultStatus.Failed);
        }
    }

    private static string GenerateTransactionHash(Guid paymentId, DateTime createdAt)
    {
        // Simple hash generation for blockchain-like transaction hash
        // In real implementation, this would be generated by actual blockchain
        var input = $"{paymentId}{createdAt:yyyyMMddHHmmss}";
        var hashBytes = System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(input));
        return Convert.ToHexString(hashBytes)[..16]; // Take first 16 characters
    }
} 